#Default config: https://github.com/KaiKikuchi/QuickShop/blob/master/src/main/resources/config.yml

#Do not touch this if you don't know what it means.
config-version: 8

#Do not touch if you not know what is this.
dev-mode: false

#Tax amount (decimal) - Eg, P1 buys $50 worth of stuff from P2.  Therefore, P1 loses $50, P2 gains $(1-0.05)*50, and tax-account gains $(0.05)*50.
tax: 0.05

#The fake player who takes tax.
tax-account: tax

#Whether or not to show taxes paid when selling to a shop.
show-tax: false

#Should we log transactions/creations to Bukkit\Plugins\QuickShop\qs.log?
log-actions: true

#For item-item based economies that don't use virtual currency.
whole-number-prices-only: false

#Force bukkit chat handler (https://github.com/KaiKikuchi/QuickShop/issues/10)
force-bukkit-chat-handler: false

#Disable QuickShop-Reremake send anonymous metrics data to bStats.
disabled-metrics: false

#Should allow QS to check for updates on SpigotMC.org?
updater: true

database:
    mysql: false
    host: localhost
    port: 3306
    database: quickshop
    user: root
    password: passwd
    # Set prefix to "none" to remove prefix
    prefix: none
    # Beta! Use your own risk! Auto-Reconnect
    reconnect: false
    # Beta! Use VARCHAR for database to solve exception: "com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'owner' used in key specification without a key length"
    # If you are using SQLite or all right, Please do not turn on this.
    use-varchar: false
    
#Limits the number of shops a person can create and own at a single time.
limits:
    #Disable this if you dont want limits on shop creation. If this is false, the rest of this section is ignored
    use: false
    
    #The default number of shops players can make
    default: 10
    
    #Players with these permissions can create these amounts of shops.
    ranks:
        #Anyone with 'quickshop.vip' permissions, can create 20 shops instead of 10.
        quickshop.vip: 20 #Players with quickshop.vip can make 20 shops.

#A list of block (materials) which can be used to create shops.
#By default, chests are added to this list.
#This will only work for blocks which implement InventoryHolder
#in other words, no enderchest shops, no shops on dirt blocks, etc.
#May cause unexpected behaviour with some blocks... Eg don't make a 
#shop on a hopper (It sucks the display item in) and furnace shops
#allow players to put whatever item they want in all 3 slots and
#dispenser shops aren't protected from redstone... Etc.
shop-blocks:
    - CHEST
    - TRAPPED_CHEST

shop:
    #Cost to make a shop
    cost: 10
    #Refund if a shop is deleted/broken/removed
    refund: false

    #Whether if there should or shouldn't be a fee for changing prices on a shop (Help deter endless undercutting)
    price-change-requires-fee: true
    #Cost of changing shop price if value above is true
    fee-for-price-change: 50

    #Lock shops so that player cannot steal from them
    lock: true
    
    #Requies a player to sneak to create and use shops if se to true
    sneak-to-create: false
    sneak-to-trade: false
    sneak-to-control: false
    
    #Sign will automaticly be created on chest if value is true
    auto-sign: true
    
    #If a player owns an unlimited shop, should they receive the cash from it or not?
    #If you buy from YOUR unlimited shop, you will NEVER be charged, regardless of this setting
    pay-unlimited-shop-owners: false
    
    #Free if player buys from their own shop
    bypass-owner-check: false
    
    #Items float above their respective chests. Items may duplicate if on large servers, specificly modded ones.
    display-items: true
    
    #The plugin will check if the display item is in a valid position every the specified amount of ticks. 0 to disable.
    display-items-check-ticks: 0
    
    #Use name SafeGuard. Highly recommended to be turned on. If having trouble with other DropItem holo displays, disable there instead. MAY CAUSE ISSUES IF FALSE.
    display-item-use-name: true
    
    #How far the /qs find <item> command will search
    #This command lets users shop quickly without wasting time searching
    #Over 100 will cause a lot of lag, so be careful and don't overdo it. 
    find-distance: 45
    
    #If vault doesnt return a currency symbol, QuickShop will use this symbol to replace it.
    alternate-currency-symbol: '$'

#List of items to disallow selling of.  Anyone with quickshop.bypass.<itemID> can bypass it    
blacklist:
- Bedrock

# custom-potions-name:
  # sign:
    # format: "%variety%type"
    # variety:
      # normal: ""
      # splash: "Splash"
      # lingering: "Ling"
  # shopinfo:
    # format: "%variety %type"
    # variety:
      # normal: ""
      # splash: "Splash"
      # lingering: "Lingering"

  # #Custom names for potions types. Format: <PotionType>;<CustomSignName>;<CustomFullName>
  # # PotionType: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionType.html
  # types:
  # - INVISIBILITY;Invis;Invisibility

  # #Custom names for potion effect type. Format: <PotionEffectType>;<CustomName>
  # # PotionEffect: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
  # effects:
  # - FIRE_RESISTANCE;Fire resistance
  # - INVISIBILITY;Invisibility

#WARNING! These are all in testing!
protect:
  #Protect shop items from hopper minecarts (Will destroy minecart)
  minecart: true
  #Protect shops from entities picking them up
  entity: true
  #Protect shop items from being activated by redstone
  redstone: true
  #Protect shops from being broken by plants and structures being grown.
  structuregrow: true
  #Protect shops from explosions
  explode: true
  #Protect shops from being emptied by a hopper
  hopper: true
lockette:
  private: "[Private]"
  more_users: "[More Users]"
  #Protect shops from being broken
#Float items advanced filter manager
#These are all in testing and have many bugs, use at your own risk!
float:
  enable: false
  #If this is disabled, all options after this will be ignored.
  item:
    #Item filter
    enable: false
    blacklist: true
    #true = use blacklist mode, in blacklist item will disallow spawn float item
    #false = use whitelist mode, in whitelist item will allow spawn float item
    list:
    - STONE
    - GRASS
    #add item's BUKKIT NAME in there
  lore:
    enable: false
    blacklist: true
    #true = use blacklist mode, in blacklist item will disallow spawn float item
    #false = use whitelist mode, in whitelist item will allow spawn float item
    list:
      - NOT FLOAT LORE
    #add keywords in there, plugin will check it contain or not on items.
  displayname:
    enable: false
    blacklist: true
    #true = use blacklist mode, in blacklist item will disallow spawn float item
    #false = use whitelist mode, in whitelist item will allow spawn float item
    list:
    - Super Sword(Can't float)
    #add keywords in there, plugin will check it contain or not on items.
# Ongoing Fee
ongoingfee:
    enable: false
    # CheckTime unit is tick (1 seconds = 20 ticks) Do not set low than 600!
    # If you are a large server, set this kind of large.
    # Per {checkTime} to check database and withdraw once money.
    # Default: 864000    864000ticks to withdraw all players once money
    # Server reboot/reload or qs reload can stop and reset all shops timer.
    checkTime: 864000
    # Reset all shops exist time when server booting
    # If set false, Server offline time will calc in total time and withdraw money.
    # And this can cleanup schedule table old datas.
    reset-on-startup: true
    # If target player offline, QuickShop will not calc time him shops money.
    pass-offline-player: false
    # Only calc-shops set true, this option can work.
    # How many money per shop withdraw each unit time.
    shops-price: 1
